name: 'Deploy to gh-pages'
on:
  push:
    branches: ['main', 'deploy']
jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'
      - name: 'Install Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: '20.x'
      - name: 'Install NPM packages'
        run: 'npm ci'
      - name: 'Build project'
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: 'npm run build'
      - name: 'Run tests'
        run: 'npm run test'
      - name: 'Upload artifacts'
        uses: 'actions/upload-pages-artifact@v3'
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'
  deploy:
    name: 'Deploy'
    needs: 'build'
    runs-on: 'ubuntu-latest'
    permissions:
      pages: 'write'
      id-token: 'write'
    environment:
      name: 'github-pages'
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      - name: 'Deploy'
        id: 'deployment'
        uses: 'actions/deploy-pages@v4'
