name: 'Release'
on:
  push:
    tags:
      - '**'
jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Create Release'
        uses: 'softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631'
        with:
          generate_release_notes: true
